"""UI strings for Promo ROI Predictor (bilingual)."""

LANG = {
    "ja": {
        "title": "🎯 Promo ROI Predictor",
        "caption": "Uplift Modeling で販促予算を最適化する",
        "portfolio_btn": "🔗 ポートフォリオを見る",
        "portfolio_label": "ポートフォリオ",
        "data_source": "データソース",
        "data_mode_radio": "モード",
        "use_demo": "デモデータを使う",
        "upload_csv": "実データCSVをアップロード",
        "upload_label": "CSVファイルをアップロード",
        "n_samples": "生成件数",
        "seed": "ランダムシード",
        "feat_select": "使用する特徴量を選択",
        "threshold": "閾値設定",
        "uplift_thresh": "アップリフト閾値（正：効果あり / 負：逆効果）",
        "buy_thresh": "購入確率閾値（この値以上 = 購入傾向あり）",
        "run_btn": "🚀 モデルを実行",
        "running": "モデル学習・予測中...",
        "roi_params": "ROIパラメータ",
        "coupon_cost": "クーポン配布コスト（1枚あたり $）",
        "aov": "平均注文額（$）",
        "margin": "粗利率（%）",
        "seg_result": "📊 4象限セグメント分類",
        "bubble_title": "アップリフトスコア × 購入確率（コントロール群）",
        "roi_title": "💰 ROI比較",
        "all_customers": "全員にクーポン配布",
        "targeted": "説得可能層のみに配布",
        "coupon_spend": "クーポン費用",
        "uplift_rev": "増分売上（粗利）",
        "net": "純利益",
        "saving": "クーポン費用の節約",
        "seg_table": "📋 セグメント別集計",
        "seg_col": "セグメント",
        "n_col": "人数",
        "pct_col": "割合",
        "avg_uplift": "平均アップリフト",
        "avg_p_treat": "平均購入率(クーポンあり)",
        "avg_p_ctrl": "平均購入率(クーポンなし)",
        "download": "📥 予測スコアをダウンロード",
        "csv_label": "customer_scores.csv",
        "no_data": "データを選択して「モデルを実行」を押してください",
        "seg_profile": "🔍 セグメント別キャラクター分析",
        "avg_label": "平均値",
        "feat_profile": "各セグメントの顧客特徴",
        "feat_profile_cap": (
            "※ 数値は各特徴量を0〜1に正規化した相対値です。"
            "1.0に近いほどそのセグメントでその特徴が強く現れています。"
        ),
        "feat_dist_title": "📊 特徴量分布比較",
        "feat_imp_title": "🔑 各セグメントを判別する特徴量の重要度",
        "feat_imp_cap": (
            "※ One-vs-Restのランダムフォレストによる重要度。"
            "値が大きいほどそのセグメントを他と区別するのにその特徴量が強く効いています。"
        ),
        "persona_title": "👤 セグメントペルソナ",
        "csv_desc": "必要なカラム：",
        "csv_col1": "• customer_id：顧客ID（整数）",
        "csv_col2": "• treatment：クーポン配布（1=あり / 0=なし）",
        "csv_col3": "• conversion：購入（1=あり / 0=なし）",
        "csv_col4": "• 特徴量：年齢・購買額等（数値）",
        "csv_example": (
            "例）customer_id,treatment,conversion,age,past_spend\n1,1,1,35,250\n2,0,0,52,80"
        ),
    },
    "en": {
        "title": "🎯 Promo ROI Predictor",
        "caption": "Optimize your promotional budget with Uplift Modeling",
        "portfolio_btn": "🔗 View Portfolio",
        "portfolio_label": "Portfolio",
        "data_source": "Data Source",
        "data_mode_radio": "Mode",
        "use_demo": "Use demo data",
        "upload_csv": "Upload real data CSV",
        "upload_label": "Upload CSV file",
        "n_samples": "Number of samples",
        "seed": "Random seed",
        "feat_select": "Select features to use",
        "threshold": "Threshold Settings",
        "uplift_thresh": "Uplift threshold (positive = effect / negative = backfire)",
        "buy_thresh": "Purchase probability threshold (above = likely buyer)",
        "run_btn": "🚀 Run Model",
        "running": "Training model and predicting...",
        "roi_params": "ROI Parameters",
        "coupon_cost": "Coupon cost per customer ($)",
        "aov": "Average order value ($)",
        "margin": "Gross margin (%)",
        "seg_result": "📊 4-Quadrant Segment Classification",
        "bubble_title": "Uplift Score × Purchase Probability (Control)",
        "roi_title": "💰 ROI Comparison",
        "all_customers": "Send to all customers",
        "targeted": "Send to Persuadables only",
        "coupon_spend": "Coupon cost",
        "uplift_rev": "Incremental revenue (gross profit)",
        "net": "Net profit",
        "saving": "Coupon budget saved",
        "seg_table": "📋 Segment Summary",
        "seg_col": "Segment",
        "n_col": "Count",
        "pct_col": "Share",
        "avg_uplift": "Avg Uplift",
        "avg_p_treat": "Avg P(buy|coupon)",
        "avg_p_ctrl": "Avg P(buy|no coupon)",
        "download": "📥 Download Prediction Scores",
        "csv_label": "customer_scores.csv",
        "no_data": "Select data and click 'Run Model'",
        "seg_profile": "🔍 Segment Character Analysis",
        "avg_label": "Average",
        "feat_profile": "Customer Profile by Segment",
        "feat_profile_cap": (
            "Values are normalized (0–1) per feature. "
            "1.0 means that segment scores highest on that feature across all segments."
        ),
        "feat_dist_title": "📊 Feature Distribution by Segment",
        "feat_imp_title": "🔑 Feature Importance for Segment Classification",
        "feat_imp_cap": (
            "One-vs-Rest Random Forest importance. "
            "Higher = that feature more strongly distinguishes the segment from others."
        ),
        "persona_title": "👤 Segment Personas",
        "csv_desc": "Required columns:",
        "csv_col1": "• customer_id: customer ID (integer)",
        "csv_col2": "• treatment: coupon sent (1=yes / 0=no)",
        "csv_col3": "• conversion: purchased (1=yes / 0=no)",
        "csv_col4": "• features: age, spend, etc. (numeric)",
        "csv_example": (
            "e.g. customer_id,treatment,conversion,age,past_spend\n1,1,1,35,250\n2,0,0,52,80"
        ),
    },
}
